
#------------- Build Stage -------------#
FROM python:3.13-alpine AS builder

WORKDIR /app

COPY ./requirements.txt . 

RUN pip install --prefix /install --no-cache-dir -r requirements.txt

COPY . . 

#------------- Runtime Stage -------------#
FROM python:3.13-alpine

WORKDIR /app 

# Copy installed Python packages from builder stahe 
COPY --from=builder /install /usr/local 

COPY --from=builder /app .

EXPOSE 5000 

CMD ["python3", "./app.py"]