name: Publish Docker Image 
run-name: Docker build by ${{ github.actor }}. 🚀
on:
  push: 
   branches: 
   - main 



## on push to main 
## rebuild image 
## login to contianer registrsy 
## tag image 
## push to image registry